### ISSUE TITLE
Can't use reject promise

### ISSUE THREAD

**Issue by hahunavth** [hahunavth/ReduxToolkit_TodoApp#1]
### File: src/Components/Todos.jsx

>   PromiseLike.then<TResult1 = T, TResult2 = never>(onfulfilled?: (value: T) => TResult1 | PromiseLike<TResult1>, onrejected?: (reason: any) => TResult2 | PromiseLike<TResult2>): PromiseLike<TResult1 | TResult2>
The callback to execute when the Promise is resolved.

> Attaches callbacks for the resolution and/or rejection of the Promise.

> @returns — A Promise for the completion of which ever callback is executed.

**src/Components/Todos.jsx**
```js
  useEffect(() => {
    dispatch(getTodo())
    .then((value) => {
      setIsFulifilled(true)
      setLoaded(true)
      console.log(value)
    },
    (reason) => {
      setIsFulifilled(false)
      setLoaded(true)
      console.log(reason)
    })
  }, [dispatch])
```

**Request Header**
```bash
GET /todos undefined
Host: hahunavth-rails-api.herokuapp.com
User-Agent: Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:89.0) Gecko/20100101 Firefox/89.0
Accept: application/json, text/plain, */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Origin: http://localhost:3000
Connection: keep-alive
Referer: http://localhost:3000/
If-None-Match: W/"2a840031caf1182e147022e6aea8588b"
Cache-Control: max-age=0
```

**Response**
```bash
{type: "todos/todosFetched/rejected", payload: undefined, meta: {…}, error: {…}}
error:
message: "Network Error"
name: "Error"
stack: "Error: Network Error\n    at createError (http://localhost:3000/ReduxToolkit_TodoApp/static/js/0.chunk.js:6329:15)\n    at XMLHttpRequest.handleError (http://localhost:3000/ReduxToolkit_TodoApp/static/js/0.chunk.js:5823:14)"
__proto__: Object
meta:
aborted: false
arg: undefined
condition: false
rejectedWithValue: false
requestId: "ZZ4u5Nqx03Ow_yNPIrBQ-"
requestStatus: "rejected"
__proto__: Object
payload: undefined
type: "todos/todosFetched/rejected"
__proto__: Object
```

**Comment by hahunavth** [comment]
**src/Components/Reducer/TodoSlice.js**

```js
const todosSlice = createSlice({
  name: "todos",
  initialState: {
    allTodos: [],
  },
  reducers: {
    addTodos: {
      reducer: (state, action) => {
        state.allTodos.unshift(action.payload);
      },
      prepare: (title) => {
        return {
          payload: { id: nanoid(), title: title, completed: false },
        };
      },
    },
    removeTodos: (state, action) => {
      const id = action.payload;
      state.allTodos = state.allTodos.filter((todo) => {
        return todo.id !== id;
      });
    },
    markComplete: (state, action) => {
      const id = action.payload;
      state.allTodos = state.allTodos.map((todo) => {
        if (todo.id === id) {
          todo.completed = !todo.completed;
        }
        return todo;
      });
    },
  },
  extraReducers: {
    // Get all todos
    [getTodo.pending]: (state, action) => {
      console.log("Fetching todos from backend ....");
    },
    // [getTodo.rejected]: (state, action) => {
    //   console.log("Rejected");
    //   state.allTodos = [];
    //   // return new Promise(() => {});
    // },
    [getTodo.fulfilled]: (state, action) => {
      console.log("Done");
      state.allTodos = action.payload;
    },
    [addTodo.pending]: (state, action) => {
      console.log("try add todo");
    },
    [addTodo.fulfilled]: (state, action) => {
      const title = action.payload;
      const id = action.payload.id;
      state.allTodos.unshift(title);
    },
    [removeTodo.pending]: (state, action) => {
      console.log("try delete todo");
    },
    [removeTodo.fulfilled]: (state, action) => {
      const id = action.payload.id;
      state.allTodos = state.allTodos.filter((todo) => {
        return todo.id !== id;
      });
    },
  },
});
```
